### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Cybo1927** [Cybo1927/Hosts#82]
### _Expected to be finished by March 31, 2021_
- [x] Work to make each of my lists more uniform. Also check for typos, double spacing, and find as many dead domains as possible.

### _Expected to be finished by June 30, 2021_
- [x] Do heavy testing of third-party only blacklists to try and prevent any an all breakage. 
* ***NOTICE: I do not use any of these services, they may break at any time. If you encounter any problems please create a new [issue](https://github.com/Cybo1927/Hosts/issues/new/choose)***
<hr>

### _Expected to be finished by January 31, 2021_
- [x] Make [Anti-corp](https://github.com/Cybo1927/Hosts/tree/master/Anti-corp) lists more uniform (Create a template and work with it in every file)

### _Expected to be finished by N/A_
- [x] Make blacklists in [Anti-corp](https://github.com/Cybo1927/Hosts/tree/master/Anti-corp) to block the corporations only on third-party sites while keeping their own working; only plausible ones. Some will never run on third-party sites.
